name: CustomMotd
version: ${project.version}
main: me.sendpacket.custommotd.CustomMotd
api-version: 1.13
authors: [SendPacket]
commands:
  cmotd:
    description: Modify the MOTD of the Server
    permission: cmotd.use
