name: CustomMotd
version: ${project.version}
main: me.sendpacket.custommotd.CustomMotd
api-version: 1.13
authors: [SendPacket]
commands:
  cmotd:
    description: Reload the MOTD from the Config File.
    permission: cmotd.reload
